guys=[	
"Agudelo, Victor	",
"Amevor, Denzel	",
"Anderson, Ben	",
"Ansari, Naumaan	",
"Bartlett, Chris	",
"Brown, Nick	",
"Buxton, Tanner	",
"Calzada, Derek	",
"Carnavale, Frank	",
"Childs, Andrew	",
"Clark, Matthew	",
"Collins, Joey	",
"Couitt, Stephen	",
"DeFreitas, Timothy	",
"Dresser, Anthony	",
"Fiero, Dan McVero	",
"Fox, Alex	",
"Galati, Corin	",
"Gaudet, Ben	",
"Gonzalez, Daniel	",
"Gould, Scott	",
"Gruenbaum, Henry	",
"Hammond, Oliver	",
"Hennrikus, Ryan	",
"Hudson, Andrew	",
"Jackson, Gary	",
"Kane, Pat	",
"Karcs, Adam	",
"LaJeunesse, Nick	",
"LaRochelle, Bryan	",
"Lee, Foster	",
"Malcolm, Richard	",
"Nieves, Larry	",
"Perrault, Luke	",
"Perrone, Michael	",
"Pickering, Adrian	",
"Raymond, Grant	",
"Reynolds, Andrew	",
"Roche, Logan	",
"Rocks, Trevor	",
"Rojas, Santiago	",
"Rojas, Sebastian	",
"Sears, Zach	",
"Shaw, Brandon	",
"Shi, Eric	",
"Silva, Nick	",
"Simon, Phil	",
"Smith, Cameron	",
"Spicola, Joey	",
"Stewart, Zach	",
"Taylor, Adam	",
"Turner, Ryan	",
"Vandenberg, Halsey	",
"Zapatka, Zak	"
];


for(var i = 0; i < guys.length; i++){
	formatted = guys[i].trim().split(',');
	formatted = formatted[formatted.length - 1].trim() + " " + formatted[0];

	console.log(formatted);
	$.post('/Guests/create',{name: formatted, gender: 'M', addedBy: 'drob@wpi.edu'},function(){
		console.log('added');
	});
}

girls = ["Acevedo, Michelle	",
"Aherarra, Celina	",
"Ahererra, Celina	",
"Aiello, Christina	",
"Alameda, Mackenzie	",
"Antolick, Sarah	",
"Bacellar, Tati	",
"Bailey, Sarah	",
"Baker, Nicole	",
"Baltazar, Amanda	",
"Balthzar, Amanda	",
"Barolli, Rebecca	",
"Bartlett, Carrie	",
"Batbouta, Lisa	",
"Bebrin, Nicole	",
"Becker, Miri	",
"Berry, Grace	",
"Berryman, Michelle	",
"Bindas, Mary-Kate	",
"Bindas, Mary Kate	",
"Bindas, Mary Kate	",
"Blanker, Alaina	",
"Botelho, Victoria	",
"Bottom, Christina	",
"Bouvier, Jackie	",
"Brann, Kristen	",
"Brasser, Alison	",
"Brecher, Emily	",
"Brockway, Sarah	",
"Brofford, Kelsey	",
"Bumila, Katie	",
"Caccioppoli, Jess	",
"Cantwell, Melanie	",
"Cantwell, Meg	",
"Cantwell., Melanie	",
"Cardoza, Brynn	",
"Cardozo, Brynn	",
"Castellano, Kailey	",
"Caulaum, Jame	",
"Cerio, Alessandra	",
"Chunga, Caylee	",
"Ciesluk, Brittany	",
"Ciulla, Jessie ciulla	",
"Clasby, Kristina	",
"Coia, Cecily coia	",
"Colcord, Brittany	",
"Collins, Falisha	",
"Collins, Ashleigh	",
"Conklin, Angela	",
"Conlom, Chelsea	",
"Costa, Chelsea	",
"Cowan, Melissa	",
"Cuilla, Jessie	",
"DaBoll-Lavoie, Abby	",
"Davis, Linette	",
"DeBaie, Analise	",
"Desmond, Jess	",
"DiGioia, Andrea	",
"DiTroia, Jacquelyne	",
"Dickerson, Kellie	",
"Dighello, Lea	",
"Donahue, Alyssa	",
"Donohue, Alyssa	",
"Doolin, Clare	",
"Draper, Becca	",
"Durr, Alanah	",
"Dutra, Tina	",
"Eastaugh, Jenny	",
"Edwards, Nadjia	",
"Erlick, Mimi	",
"Fanciullo, Marina	",
"Fanning, Jackie	",
"Fillipone, Mikayla	",
"Fitch, Lizzy	",
"Fitch, Karen	",
"Flynn, Juli	",
"Foote, Sam	",
"Fortin, Sarah	",
"Freed, Margaret	",
"Gallagher, Hannah	",
"Garbir, Sarge	",
"Garcia-Fine, Sandra	",
"Gardiner, Sarah	",
"Geer, Emily	",
"Golsher, Anetta	",
"Goncalaves, Brianna	",
"Goodwin, Meghan	",
"Gouzias, Hannah	",
"Grimes, Victoria	",
"Haughn, Melissa	",
"Heislein, Emily	",
"Hennessey, Meghan	",
"Hennessy, Jillian	",
"Henry, Roisin	",
"Hill, Hannah	",
"Hiznay, Alexa	",
"Hock, Lindsay	",
"Howard, Grace	",
"Hulburt, Tessa	",
"Humphrey, Morgan	",
"Hunt, Lauren	",
"Iorio, Mary	",
"Ippolitto, Amanda	",
"Jacobsen, Anne	",
"Jones, Heather	",
"Jones, Courtney	",
"Jones, Serissa	",
"Jones, Sydney	",
"Jones, Brittany	",
"Juera, Meredith	",
"Kacoyannakis, Kayli	",
"Katherine, Sarah	",
"Kennedy, Rachel	",
"Khurana, Sakshi	",
"Knott, Catherine Bean	",
"Komara, Rachel	",
"Krishnan, Manisha	",
"Krupp, Kelsey	",
"LaRoche, Erin	",
"Labbay, Kaitlyn	",
"Lally, Jenny	",
"Landers, Becca	",
"Larson, Jessica	",
"Lavoie, Abby	",
"Lei, Melinda	",
"Lellman, Molly	",
"Levy, Camille	",
"Linch, Molly	",
"Lyles, Chandlor	",
"Machlin, Emily	",
"Madeiros, Dayna	",
"Mardoza, Raquel	",
"Marsh, Sanara	",
"Marvasti-Sitterly, Mitra	",
"Mateo, Ana	",
"McAloon, Amanda	",
"McCallum, Hannah	",
"McDrew, Alandra	",
"McHugh, Devyn	",
"Mcgee, Drob Tits	",
"Melchert, Victoria	",
"Merrill, Laura	",
"Miller, Julia	",
"Miller, Paula	",
"Morgan, Ashley	",
"Morgan, Kelly	",
"Musteata, Elena	",
"Neeno, Samantha	",
"Newell, Katie	",
"Newman, Rita	",
"Nolan, Kristen	",
"OConnor, Lauren	",
"Obaldia, Mariana De	",
"Ober, Jen	",
"Ouellette, Noelle	",
"Oulette, Noelle	",
"Pacht, Emily	",
"Parker, Sarah	",
"Pasciuto, Mickey	",
"Pasciuto, Mikayla	",
"Pasciutto, Mickey	",
"Pepo, Maris	",
"Perera, Brigitte	",
"Perez, Jasmine	",
"Petock, Rose	",
"Phillips, Madeline	",
"Pierce, Jamie	",
"Piscitelli, Stephanie	",
"Pizzimenti, Charlene	",
"Poop, hello poop	",
"Poss, Kaitlyn	",
"Prescott, Rachel	",
"Preston, Monica	",
"Puishys, Lauren	",
"Quatieri, Sarah	",
"Racicot, Amanda	",
"Rahman, Saraf	",
"Raymond, Emma	",
"Reinertsen, Hannah	",
"Reyes, Adrianna	",
"Rhodes, Brittany	",
"Riccardi, Danielle	",
"Ricci, Sam	",
"Rivard, Ally	",
"Roberts, Emma	",
"Robinson, Hannah robinson	",
"Rombola, Jordyn	",
"Rota, Casey	",
"Roth, Sarah	",
"Roy, Taryn	",
"Roy, Kaija	",
"Ruiz, Daniela	",
"Sachar, Saloni	",
"Salerno, Paige	",
"Sandgren, Hayley	",
"Sarchar, Soloni	",
"Savasan, Ceren	",
"Sawicki, Meghan	",
"Schulman, Illiana	",
"Seibring, Emily	",
"Shandrow, Nicky	",
"Sheldon, Kristen	",
"Simpson, Alexis	",
"Sisson, Sarah	",
"Smith, Ashley	",
"Smith, Melanie	",
"Snyder, Ashley	",
"Spofford, Tori	",
"Stacy, Cassandra	",
"Stergiou, Kelsey	",
"Stueber, Deanna	",
"Sundberg, Kristin	",
"Terravecchia, Gianna	",
"Thayer, Sarah	",
"Thibault, Allie	",
"Thompson, Layla	",
"Tomida, Mai	",
"Tran, Lina	",
"Travinson, Cheryl	",
"Trivedi, Crystal	",
"Truong, Julia	",
"Tucker, Sydney	",
"Tupaj, Katie	",
"Ullery, Heather	",
"Valcour, Victoria	",
"Verdel-Ogden, Courtney	",
"Warner, Marisa	",
"Williams, Jessica	",
"Williams, Erin	",
"Wilson, Lindsey	",
"Wisheart, Danielle	",
"Wright, Katie	",
"Yee, Nicolette	",
"Z, Natalia	",
"Zawada, Angelica	",
"Zelinski, Kim	",
"Zhang, Mindy	",
"Zhang, Hedan Mindy	",
"Ziegler, Kathryn"];


for(var i = 0; i < girls.length; i++){
	formatted = girls[i].trim().split(',');
	formatted = formatted[formatted.length - 1].trim() + " " + formatted[0];

	console.log(formatted);
	$.post('/Guests/create',{name: formatted, gender: 'F', addedBy: 'drob@wpi.edu'},function(){
		console.log('added');
	});
}

for(var i = 826; i < 849; i++){
	deleteUser(i);
}

$('.guest-entry.editable').each(function(){
	var name = $(this).val();
	if($(this).val().indexOf('%20') > 0){
		$.post('/Guests/delete',{addedBy: 'drob@wpi.edu'},function(resp){console.log(response)});
	}
});


function deleteUser(id){
		$.ajax({
	    url: '/Guests/' + id,
	    type: 'DELETE',
	    success: function(result) {
	        console.log(id + ' deleted');
	    }
	});
}