guys=[	
"Agudelo, Victor	",
"Amevor, Denzel	",
"Anderson, Ben	",
"Ansari, Naumaan	",
"Bartlett, Chris	",
"Brown, Nick	",
"Buxton, Tanner	",
"Calzada, Derek	",
"Carnavale, Frank	",
"Childs, Andrew	",
"Clark, Matthew	",
"Collins, Joey	",
"Couitt, Stephen	",
"DeFreitas, Timothy	",
"Dresser, Anthony	",
"Fiero, Dan McVero	",
"Fox, Alex	",
"Galati, Corin	",
"Gaudet, Ben	",
"Gonzalez, Daniel	",
"Gould, Scott	",
"Gruenbaum, Henry	",
"Hammond, Oliver	",
"Hennrikus, Ryan	",
"Hudson, Andrew	",
"Jackson, Gary	",
"Kane, Pat	",
"Karcs, Adam	",
"LaJeunesse, Nick	",
"LaRochelle, Bryan	",
"Lee, Foster	",
"Malcolm, Richard	",
"Nieves, Larry	",
"Perrault, Luke	",
"Perrone, Michael	",
"Pickering, Adrian	",
"Raymond, Grant	",
"Reynolds, Andrew	",
"Roche, Logan	",
"Rocks, Trevor	",
"Rojas, Santiago	",
"Rojas, Sebastian	",
"Sears, Zach	",
"Shaw, Brandon	",
"Shi, Eric	",
"Silva, Nick	",
"Simon, Phil	",
"Smith, Cameron	",
"Spicola, Joey	",
"Stewart, Zach	",
"Taylor, Adam	",
"Turner, Ryan	",
"Vandenberg, Halsey	",
"Zapatka, Zak	"
];


for(var i = 0; i < guys.length; i++){
	formatted = guys[i].trim().split(',');
	formatted = formatted[formatted.length - 1].trim() + " " + formatted[0];

	console.log(formatted);
	$.post('/Guests/create',{name: formatted, gender: 'M', addedBy: 'drob@wpi.edu'},function(){
		console.log('added');
	});
}

girls = ["Acevedo, Michelle	",
"Aherarra, dfCelina	",
"Ahererra, dfCelina	",
"Aiello, dfChristina	",
"Alameda, dfMackenzie	",
"Antolick, dfSarah	",
"Bacellar, dfTati	",
"Bailey, dfSarah	",
"Baker, dfNicole	",
"Baltazar, dfAmanda	",
"Balthzar, dfAmanda	",
"Barolli, dfRebecca	",
"Bartlett, dfCarrie	",
"Batbouta, dfLisa	",
"Bebrin, dfNicole	",
"Becker, dfMiri	",
"Berry, dfGrace	",
"Berryman, dfMichelle	",
"Bindas, Mary-dfKate	",
"Bindas, Mary dfKate	",
"Bindas, Mary dfKate	",
"Blanker, dfAlaina	",
"Botelho, dfVictoria	",
"Bottom, dfChristina	",
"Bouvier, dfJackie	",
"Brann, dfKristen	",
"Brasser, dfAlison	",
"Brecher, dfEmily	",
"Brockway, dfSarah	",
"Brofford, dfKelsey	",
"Bumila, dfKatie	",
"Caccioppoli, dfJess	",
"Cantwell, dfMelanie	",
"Cantwell, dfMeg	",
"Cantwell., dfMelanie	",
"Cardoza, dfBrynn	",
"Cardozo, dfBrynn	",
"Castellano, dfKailey	",
"Caulaum, dfJame	",
"Cerio, dfAlessandra	",
"Chunga, dfCaylee	",
"Ciesluk, dfBrittany	",
"Ciulla, Jessie dfciulla	",
"Clasby, dfKristina	",
"Coia, Cecily dfcoia	",
"Colcord, dfBrittany	",
"Collins, dfFalisha	",
"Collins, dfAshleigh	",
"Conklin, dfAngela	",
"Conlom, dfChelsea	",
"Costa, dfChelsea	",
"Cowan, dfMelissa	",
"Cuilla, dfJessie	",
"DaBoll-Lavoie, dfAbby	",
"Davis, dfLinette	",
"DeBaie, dfAnalise	",
"Desmond, dfJess	",
"DiGioia, dfAndrea	",
"DiTroia, dfJacquelyne	",
"Dickerson, dfKellie	",
"Dighello, dfLea	",
"Donahue, dfAlyssa	",
"Donohue, dfAlyssa	",
"Doolin, dfClare	",
"Draper, dfBecca	",
"Durr, dfAlanah	",
"Dutra, dfTina	",
"Eastaugh, dfJenny	",
"Edwards, dfNadjia	",
"Erlick, dfMimi	",
"Fanciullo, dfMarina	",
"Fanning, dfJackie	",
"Fillipone, dfMikayla	",
"Fitch, dfLizzy	",
"Fitch, dfKaren	",
"Flynn, dfJuli	",
"Foote, dfSam	",
"Fortin, dfSarah	",
"Freed, dfMargaret	",
"Gallagher, dfHannah	",
"Garbir, dfSarge	",
"Garcia-Fine, dfSandra	",
"Gardiner, dfSarah	",
"Geer, dfEmily	",
"Golsher, dfAnetta	",
"Goncalaves, dfBrianna	",
"Goodwin, dfMeghan	",
"Gouzias, dfHannah	",
"Grimes, dfVictoria	",
"Haughn, dfMelissa	",
"Heislein, dfEmily	",
"Hennessey, dfMeghan	",
"Hennessy, dfJillian	",
"Henry, dfRoisin	",
"Hill, dfHannah	",
"Hiznay, dfAlexa	",
"Hock, dfLindsay	",
"Howard, dfGrace	",
"Hulburt, dfTessa	",
"Humphrey, dfMorgan	",
"Hunt, dfLauren	",
"Iorio, dfMary	",
"Ippolitto, dfAmanda	",
"Jacobsen, dfAnne	",
"Jones, dfHeather	",
"Jones, dfCourtney	",
"Jones, dfSerissa	",
"Jones, dfSydney	",
"Jones, dfBrittany	",
"Juera, dfMeredith	",
"Kacoyannakis, dfKayli	",
"Katherine, dfSarah	",
"Kennedy, dfRachel	",
"Khurana, dfSakshi	",
"Knott, Catherine dfBean	",
"Komara, dfRachel	",
"Krishnan, dfManisha	",
"Krupp, dfKelsey	",
"LaRoche, dfErin	",
"Labbay, dfKaitlyn	",
"Lally, dfJenny	",
"Landers, dfBecca	",
"Larson, dfJessica	",
"Lavoie, dfAbby	",
"Lei, dfMelinda	",
"Lellman, dfMolly	",
"Levy, dfCamille	",
"Linch, dfMolly	",
"Lyles, dfChandlor	",
"Machlin, dfEmily	",
"Madeiros, dfDayna	",
"Mardoza, dfRaquel	",
"Marsh, dfSanara	",
"Marvasti-Sitterlydf, Mitra	",
"Mateo, dfAna	",
"McAloon, dfAmanda	",
"McCallum, dfHannah	",
"McDrew, dfAlandra	",
"McHugh, dfDevyn	",
"Mcgee, Drob dfTits	",
"Melchert, dfVictoria	",
"Merrill, dfLaura	",
"Miller, dfJulia	",
"Miller, dfPaula	",
"Morgan, dfAshley	",
"Morgan, dfKelly	",
"Musteata, dfElena	",
"Neeno, dfSamantha	",
"Newell, dfKatie	",
"Newman, dfRita	",
"Nolan, dfKristen	",
"OConnor, dfLauren	",
"Obaldia, Mariana dfDe	",
"Ober, dfJen	",
"Ouellette, dfNoelle	",
"Oulette, dfNoelle	",
"Pacht, dfEmily	",
"Parker, dfSarah	",
"Pasciuto, dfMickey	",
"Pasciuto, dfMikayla	",
"Pasciutto, dfMickey	",
"Pepo, dfMaris	",
"Perera, dfBrigitte	",
"Perez, dfJasmine	",
"Petock, dfRose	",
"Phillips, dfMadeline	",
"Pierce, dfJamie	",
"Piscitelli, dfStephanie	",
"Pizzimenti, dfCharlene	",
"Poop, hello dfpoop	",
"Poss, dfKaitlyn	",
"Prescott, dfRachel	",
"Preston, dfMonica	",
"Puishys, dfLauren	",
"Quatieri, dfSarah	",
"Racicot, dfAmanda	",
"Rahman, dfSaraf	",
"Raymond, dfEmma	",
"Reinertsen, dfHannah	",
"Reyes, dfAdrianna	",
"Rhodes, dfBrittany	",
"Riccardi, dfDanielle	",
"Ricci, dfSam	",
"Rivard, dfAlly	",
"Roberts, dfEmma	",
"Robinson, dfHannah robinson	",
"Rombola, dfJordyn	",
"Rota, dfCasey	",
"Roth, dfSarah	",
"Roy, dfTaryn	",
"Roy, dfKaija	",
"Ruiz, dfDaniela	",
"Sachar, dfSaloni	",
"Salerno, dfPaige	",
"Sandgren, dfHayley	",
"Sarchar, dfSoloni	",
"Savasan, dfCeren	",
"Sawicki, dfMeghan	",
"Schulman, dfIlliana	",
"Seibring, dfEmily	",
"Shandrow, dfNicky	",
"Sheldon, dfKristen	",
"Simpson, dfAlexis	",
"Sisson, dfSarah	",
"Smith, dfAshley	",
"Smith, dfMelanie	",
"Snyder, dfAshley	",
"Spofford, dfTori	",
"Stacy, dfCassandra	",
"Stergiou, dfKelsey	",
"Stueber, dfDeanna	",
"Sundberg, dfKristin	",
"Terravecchia, dfGianna	",
"Thayer, dfSarah	",
"Thibault, dfAllie	",
"Thompson, dfLayla	",
"Tomida, dfMai	",
"Tran, dfLina	",
"Travinson, dfCheryl	",
"Trivedi, dfCrystal	",
"Truong, dfJulia	",
"Tucker, dfSydney	",
"Tupaj, dfKatie	",
"Ullery, dfHeather	",
"Valcour, dfVictoria	",
"Verdel-Ogden, dfCourtney	",
"Warner, dfMarisa	",
"Williams, dfJessica	",
"Williams, dfErin	",
"Wilson, dfLindsey	",
"Wisheart, dfDanielle	",
"Wright, dfKatie	",
"Yee, dfNicolette	",
"Z, dfNatalia	",
"Zawada, dfAngelica	",
"Zelinski, dfKim	",
"Zhang, dfMindy	",
"Zhang, Hedan dfMindy	",
"Ziegler, Kathryn"];


for(var i = 0; i < girls.length; i++){
	formatted = girls[i].trim().split(',');
	formatted = formatted[formatted.length - 1].trim() + " " + formatted[0];

	console.log(formatted);
	$.post('/Guests/create',{name: formatted, gender: 'F', addedBy: 'drob@wpi.edu'},function(){
		console.log('added');
	});
}

for(var i = 826; i < 849; i++){
	deleteUser(i);
}

$('.guest-entry.editable').each(function(){
	var name = $(this).val();
	if($(this).val().indexOf('%20') > 0){
		$.post('/Guests/delete',{addedBy: 'drob@wpi.edu'},function(resp){console.log(response)});
	}
});


function deleteUser(id){
		$.ajax({
	    url: '/Guests/' + id,
	    type: 'DELETE',
	    success: function(result) {
	        console.log(id + ' deleted');
	    }
	});
}